גלובל נטוורקס scraper is done
Freshboard-city/job_scraping_demo pull request #110
Opened 2024-02-07 10:03 UTC by YehuditShrg

גלובל נטוורקס

2024-02-07 10:11 UTC, snirsh requested changes

2024-02-07 10:11 UTC, snirsh commented on Scrapers/CompanyScrapers/GlobaNetworksScraper.py
> +GlobaNetworksScraper().check_self()
```suggestion

```

2024-02-07 10:14 UTC, YehuditShrg commented on Scrapers/CompanyScrapers/GlobaNetworksScraper.py
> +GlobaNetworksScraper().check_self()
done

2024-02-08 09:49 UTC, snirsh approved these changes

2024-02-08 11:11 UTC, merged