Scraping union
Freshboard-city/job_scraping_demo pull request #41
Opened 2024-01-21 13:32 UTC by YehuditShrg

testing the screpers

2024-01-22 14:04 UTC, snirsh requested changes

2024-01-22 14:04 UTC, snirsh commented on Scrapers/CompanyScrapers/InnodataScraper.py
> +InnodataScraper().check_self()
This is probably the Error.

2024-01-22 14:07 UTC, snirsh commented on Scrapers/CompanyScrapers/InnodataScraper.py
> +InnodataScraper().check_self()
```suggestion

```

2024-01-22 14:50 UTC, snirsh commented on Scrapers/CompanyScrapers/MdihealthScraper.py
Empty file, remove

2024-01-22 14:51 UTC, snirsh commented on Scrapers/CompanyScrapers/MdihealthScraper.py
I removed it myself

2024-01-23 09:32 UTC, YehuditShrg commented
the branch is ready to merge with the main!!

2024-01-24 18:00 UTC, snirsh submitted a review, later dismissed
LGTM

2024-01-31 16:03 UTC, snirsh commented
LGTM

2024-01-31 16:21 UTC, snirsh requested changes

2024-01-31 16:21 UTC, snirsh commented on Scrapers/CompanyScrapers/SquareTalkScraper.py
> +        driver = self.selenium_url_maker(self.url)
Can't work either soup only? Without selenium?

2024-01-31 17:27 UTC, YehuditShrg commented on Scrapers/CompanyScrapers/SquareTalkScraper.py
> +        driver = self.selenium_url_maker(self.url)
I removed this scraper to a new branch,
I'll try to do it tomorrow אי"ה.
(at first glance it seems that you must wait for the elements in this page)

2024-01-31 21:26 UTC, snirsh approved these changes

2024-01-31 22:16 UTC, merged