My work day
Freshboard-city/job_scraping_demo pull request #45
Opened 2024-01-24 10:06 UTC by YehuditShrg

all the scraper (3...) that use my word day.

2024-01-24 13:32 UTC, snirsh requested changes
we can use JSON and not webdriver, no?

2024-01-24 17:56 UTC, snirsh approved these changes

2024-01-24 17:56 UTC, snirsh commented on ScrapingTools/OutsourceTools/MyWorkDay/MyWorkDayScraper.py
> +        driver = Scraper.selenium_url_maker(self.url)
Can we use requests ?

2024-01-24 17:57 UTC, snirsh requested changes
Can we try removing the driver?
Only using requests/soup is better and more stable.

WDYT?

2024-01-28 11:17 UTC, snirsh requested changes

2024-01-28 11:17 UTC, snirsh commented on ScrapingTools/OutsourceTools/MyWorkDay/MyWorkDayScraper.py
> +MyWorkDayScraper().scrape()
Remove and remove comments

2024-01-28 11:17 UTC, snirsh commented on ScrapingTools/OutsourceTools/MyWorkDay/MyWorkDayScraper.py
> +# {"total":1736,"jobPostings":[{"title":"Senior Software Engineer, GPU Communications and Networking","externalPath":"/job/US-CA-Santa-Clara/Senior-Software-Engineer--GPU-Communications-and-Networkin
What is this? 😅

2024-01-28 11:19 UTC, YehuditShrg commented on ScrapingTools/OutsourceTools/MyWorkDay/MyWorkDayScraper.py
> +# {"total":1736,"jobPostings":[{"title":"Senior Software Engineer, GPU Communications and Networking","externalPath":"/job/US-CA-Santa-Clara/Senior-Software-Engineer--GPU-Communications-and-Networkin
we try use request . it is in progress.

2024-01-28 11:21 UTC, YehuditShrg commented on ScrapingTools/OutsourceTools/MyWorkDay/MyWorkDayScraper.py
> +# {"total":1736,"jobPostings":[{"title":"Senior Software Engineer, GPU Communications and Networking","externalPath":"/job/US-CA-Santa-Clara/Senior-Software-Engineer--GPU-Communications-and-Networkin
we tried using request but it returns a JSON only with the 20 first jobs and for the next job we need to send some meta data like cookies and we face problem with it

2024-01-28 11:49 UTC, YehuditShrg commented on ScrapingTools/OutsourceTools/MyWorkDay/MyWorkDayScraper.py
> +# {"total":1736,"jobPostings":[{"title":"Senior Software Engineer, GPU Communications and Networking","externalPath":"/job/US-CA-Santa-Clara/Senior-Software-Engineer--GPU-Communications-and-Networkin
can you take a look how to solve it?

2024-02-01 11:04 UTC, closed without merging