Greenhouse no open positions
Freshboard-city/job_scraping_demo pull request #46
Opened 2024-01-24 11:12 UTC by ChanyRosental

This scrapers use greenhouse, and no open positions, so the test fails
What do we do in this case?

2024-01-24 13:23 UTC, snirsh submitted a review, later dismissed

2024-01-24 13:23 UTC, snirsh commented on Scrapers/CompanyScrapers/CodefreshScraper.py
> +CodefreshScraper().check_self()
can be removed

2024-01-24 13:23 UTC, snirsh commented on Scrapers/CompanyScrapers/NomadHealthScraper.py
> +    def scrape(self):
we can remove all the supers

2024-01-24 13:28 UTC, snirsh commented on Scrapers/CompanyScrapers/CodefreshScraper.py
> +CodefreshScraper().check_self()
```suggestion
```

2024-01-24 13:30 UTC, snirsh reviewed
remove supers

2024-01-24 15:48 UTC, snirsh requested changes
LMK WDYT

2024-01-24 15:48 UTC, snirsh commented on Scrapers/CompanyScrapers/VaretoScraper.py
> +    url = "https://boards.greenhouse.io/vareto"
`https://api.greenhouse.io/v1/boards/vareto/embed/jobs`
Check this, we can make them all over their requests API, check my other comment for the appropriate code :)

2024-01-24 15:48 UTC, snirsh commented on ScrapingTools/OutsourceTools/Greenhouse/GreenhouseScraper.py
> +        soup = self.scraping_unit(self.url)
```suggestion
        response = requests.get(self.url)

        response_json = response.json()

        for job in response_json.get('jobs'):
            self.positions.append(
                self.Position(
                    title=job['title'].strip(),
                    link=job['absolute_url'].strip(),
                    location=job['location']['name'].strip()
                )
            )
```

2024-01-28 12:46 UTC, noazinger commented on Scrapers/CompanyScrapers/VaretoScraper.py
> +    url = "https://boards.greenhouse.io/vareto"
we tried to modify the code as you mentioned 
it works when the website has no open position but if it has it gives the following error:response_json = response.json() requests.exceptions.JSONDecodeError
what was the problem with our code, can't we use it

2024-01-28 18:13 UTC, snirsh submitted a review, later dismissed

2024-01-29 09:01 UTC, snirsh commented on Scrapers/CompanyScrapers/VaretoScraper.py
> +    url = "https://boards.greenhouse.io/vareto"
Try adding headers to the request

2024-02-02 16:31 UTC, snirsh commented
Please add the option that we talked about with using two different scrapers and if one fails you run the other, for example:
```
def scrape_with_slug(self):
...
def scrape_without_slug(self):
...

def scrape(self):
    try:
        self.scrape_with_slug()
    catch e:
        self.scrape_without_slug()
```

2024-02-02 16:31 UTC, snirsh commented
Remove all the deleted files here, i dont understsand what it is

2024-02-02 16:32 UTC, snirsh requested changes
Check my comments please

2024-02-05 20:08 UTC, snirsh approved these changes

2024-02-06 08:06 UTC, merged