LarsenAndToubroScraper with passed tests.
Freshboard-city/job_scraping_demo pull request #48
Opened 2024-01-24 14:20 UTC by pessiMargalit

2024-01-25 05:39 UTC, snirsh requested changes

2024-01-25 05:39 UTC, snirsh commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +    def find_requests_url(self, my_format):
can we move this into a "tool" that finds it instead of running this logic everytime? what do u think?

2024-01-29 19:23 UTC, pessiMargalit commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +    def find_requests_url(self, my_format):
I came to the conclusion that currently there is no need for a function to find the requests because I know the URL to JSON. In the future, building a tool to find JSON would be a good idea.

2024-02-04 10:22 UTC, snirsh requested changes

2024-02-04 10:22 UTC, snirsh commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +        jobs_json_url = 'https://larsentoubrocareers.peoplestrong.com/api/cp/rest/altone/cp/jobs/v1?offset=0&limit=45'
Did you try using limit=10000

2024-02-04 10:22 UTC, snirsh commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +        for i in range(0, 945, 45):
Why 945?

2024-02-04 21:14 UTC, pessiMargalit commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +        for i in range(0, 945, 45):
I wanted to know how many jobs there are on the site - I tried scraping and it brings up a 404 status code even though the URL is correct and exists
That's why I currently wrote according to the number of jobs that exist, which is 916 - so there are JSON files up to 945.
If you have an explanation or another way to solve the 404 problem I would be happy.
(I tried changing settings in the header and it doesn't help.)
Look at the following code where there is a function whose purpose is to calculate the amount of positions
(Currently I have given up to 1000 and in any case only bring according to the amount of relevant jobs that exist)

2024-02-05 09:57 UTC, snirsh commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +        for i in range(0, 945, 45):
I don't know about the 404, but I did try their API and it seems that this code:
```
base_url = 'https://larsentoubrocareers.peoplestrong.com/api/cp/rest/altone/cp/jobs/v1?offset=0&limit=100'
        response = requests.get(base_url, headers=headers)
        if response.status_code == 200:
            res_json = response.json()
            total = res_json.get('totalRecords')
 ```
returns the total jobs, which you should use instead of hard coding 945, because tomorrow this ocmpany will have different total jobs and you'll miss it.

2024-02-05 09:59 UTC, snirsh commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +        for i in range(0, 945, 45):
so your code should be something like:
```
base_url = 'https://larsentoubrocareers.peoplestrong.com/api/cp/rest/altone/cp/jobs/v1?offset=0&limit=100'
        response = requests.get(base_url, headers=headers)
        if response.status_code == 200:
            res_json = response.json()
            total = res_json.get('totalRecords')
            urls = [base_url.replace('offset=0', f'offset={i}') for i in range(0, total, 100)]
            return urls
            ```
            
and then you can request all the jsons of those urls with futures and you'll be fine

2024-02-05 09:59 UTC, snirsh commented on Scrapers/CompanyScrapers/LarsenAndToubroScraper.py
> +        for i in range(0, 945, 45):
so your code should be something like:
```
base_url = 'https://larsentoubrocareers.peoplestrong.com/api/cp/rest/altone/cp/jobs/v1?offset=0&limit=100'
        response = requests.get(base_url, headers=headers)
        if response.status_code == 200:
            res_json = response.json()
            total = res_json.get('totalRecords')
            urls = [base_url.replace('offset=0', f'offset={i}') for i in range(0, total, 100)]
            return urls
            ```
            
and then you can request all the jsons of those urls with futures and you'll be fine

2024-02-05 10:44 UTC, snirsh approved these changes

2024-02-05 10:47 UTC, merged